---
include:
  - board: mriya_left
    artifact-name: mriya46_mx_left
  - board: mriya_right
    artifact-name: mriya46_mx_right
  - board: mriya_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: mriya46_mx_left_studio
  - board: mriya_left
    shield: settings_reset
    artifact-name: mriya46_mx_left_settings_reset
  - board: mriya_right
    shield: settings_reset
    artifact-name: mriya46_mx_right_settings_reset
